spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 625185374022-79lf2b3q4m7214nvj5jo5g6pm1icl9na.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://3.34.156.188:8080/auth/google/callback
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/the_fit
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  expiration: 30 #1min
  secretKey: mysecret
cloud:
  aws:
    s3:
      bucket: thefitbuckettesting
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAXYKJTVOEH5WX5UM6
      secretKey: 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


